/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package componenteu2;

import javax.swing.*;
import java.awt.event.*;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author gmarl
 */
public class Buscador extends javax.swing.JPanel {
    
    private String nombre;
    private String numero;
    private DefaultComboBoxModel<String> model;
    private List<String> contactos;

    /**
     * Creates new form Buscador
     */
    public Buscador() {
        initComponents();
        
         contactos = new ArrayList<>();
        contactos.add("Alan,9518907890");
        contactos.add("Ambar,9516789000");
        contactos.add("Marlen,9516866255");
        contactos.add("Maria,9513456789");
        contactos.add("Jose,9512345678");
        contactos.add("Luisa,9518765432");
        contactos.add("Carlos,9515671234");
        contactos.add("Ana,9510987654");
        contactos.add("Pedro,9514321987");
        contactos.add("Sofia,9516543210");

         model = new DefaultComboBoxModel<>(contactos.toArray(new String[0]));
        cboContactos.setModel(model);
        cboContactos.setEditable(true);
        
        JTextField editor = (JTextField) cboContactos.getEditor().getEditorComponent();
        editor.addKeyListener(new KeyAdapter() {
        public void keyReleased(KeyEvent evt) {
               String text = editor.getText();
                filter(text);
                cboContactos.showPopup();
            }
        });
    }
    
    
     private void filter(String filter) {
        DefaultComboBoxModel<String> filteredModel = new DefaultComboBoxModel<>();
        for (String item : contactos) {
            if (item.toLowerCase().contains(filter.toLowerCase())) {
                filteredModel.addElement(item);
            }
        }
        cboContactos.setModel(filteredModel);
        cboContactos.setSelectedItem(filter);
    }

    public String getNombre() {
        nombre = txtNombre.getText();
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getNumero() {
        nombre = txtNombre.getText();
        return numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }
      
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboContactos = new javax.swing.JComboBox<>();
        lblNombre = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 153, 0));

        cboContactos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar...", "Alan,9518907890", "Ambar,9516789000", "Marlen,9516866255", "Maria,9513456789", "Jose,9512345678", "Luisa,9518765432", "Carlos,9515671234", "Ana,9510987654", "Pedro,9514321987", "Sofia,9516543210", " " }));
        cboContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboContactosActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre:");

        lblNumero.setText("Número:");

        txtNombre.setText(" ");

        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jLabel3.setText("Buscador de Contacto ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/componenteu2/Chapulin.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(cboContactos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(33, 33, 33)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNombre)
                                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(28, 28, 28)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNumero)
                                .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cboContactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(lblNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
       String nombre = txtNombre.getText().trim();
        String numero = txtNumero.getText().trim();

        if (!nombre.isEmpty() && !numero.isEmpty()) {
            System.out.println("Registro exitoso: " + nombre + ", " + numero);
            contactos.add(nombre + "," + numero);  // Agrega al contacto original
            
            model.addElement(nombre + "," + numero);
            txtNombre.setText("");
            txtNumero.setText("");
            JOptionPane.showMessageDialog(this, "Contacto guardado exitosamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, ingrese el nombre y el número.");
        }
       
       // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void cboContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboContactosActionPerformed
    String selectedItem = (String) cboContactos.getSelectedItem();
        if (selectedItem != null && !selectedItem.equals("Seleccionar...")) {
            String[] parts = selectedItem.split(",");
            if (parts.length == 2) {
                txtNombre.setText(parts[0].trim());
                txtNumero.setText(parts[1].trim());
            }
        } else {
            txtNombre.setText("");
            txtNumero.setText("");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_cboContactosActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
     char c = evt.getKeyChar();
     if (!Character.isDigit(c) || txtNumero.getText().length() >= 10) { 
     evt.consume(); 
     }   // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cboContactos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
